### PR TITLE
Documentation merge

### PR DESCRIPTION
**Pull request by ValentinJSchmidt**
Now the documentation is good enough that we can merge it and put it on the main documentation branch.
In any case it's better than what we currently have.
However it is not camera-ready yet.

### CODE REVIEW

**Comment by derNarr** [comment]
The poetry.lock file should not be part of the repository IMHO. But if there is a good reason to add it, you can convince me otherwise.

Do you think it is needed?

If not, please remove it again and add it to the .gitignore.

**Review by derNarr — CHANGES_REQUESTED** [review]
Decide, if we want to add the peotry.lock file.

**Comment by ValentinJSchmidt** [comment]
I will see if the documentation builds w/o the poetry.lock file if yes I see no reason to keep it in

**Comment by ValentinJSchmidt** [comment]
The documentation build w/o the file. 
Requested changes have been fullfilled

**Review by derNarr — APPROVED** [review]
Now it looks good. Squash and merge please. Thanks!

**Comment by ValentinJSchmidt** [comment]
I will create a new branch next, since the commit messages were too numerous

**Pull request merged**
